### ISSUE TITLE
Crash when trying to telepose a grave

### ISSUE THREAD

**Issue by Ozzymud** [M4thG33k/TombManyGraves#1]
Just messing around and trying to see how griefer will grief these seeings how owner only access is a big feature. Tried to use Blood Magic teleposers (one of 3 ways I know that will move even bedrock). On activation, crash.

Crashlog: http://pastebin.com/9W8iMwry

As a sidenote/feature request could we get a way to allow somone on a server without access to creative to get our grave contents for us? This was my intent on the teleposer, move the grave to the player.

**Comment by M4thG33k** [comment]
I think I can fix that issue easily enough tomorrow. 

And I'll eventually add that type of feature in. I just wanted to get the mod out there with basic functionality for debugging purposes before introducing new features (which also have the potential to be filled with bugs).
