### ISSUE TITLE
Grave failed to be placed in world, dropped on ground. Also crashes when placed.

### ISSUE THREAD

**Issue by SilentChaos512** [M4thG33k/TombManyGraves#1]
So I was in a cave when a creeper decided to ruin my day. After dying in the explosion, I could see all my items on the ground, along with a black block with white markings (the grave block in item form). I believe I was also given the item list, as intended.

After retrieving my items and learning the identity of the mystery block, I tried placing it, with fairly predictable results: http://pastebin.com/RwAJAMtd.

I then tried the kill command, which correctly placed the grave in world and I retrieved my items from it. Everything seems to work as intended in that case. Respawning was a bit... broken (like the game wasn't entirely convinced I had died), but I don't think that was this mod's fault.

I'm guessing the explosion may have broken the grave somehow? Perhaps it needs to be placed a bit later, I'm not sure. Also making it so player-placed grave blocks don't crash the game (or making a custom ItemBlock that can't be placed, if that's doable) would be good.

**Comment by M4thG33k** [comment]
I'll see what I can do about this tomorrow. Thanks for letting me know!

**Comment by M4thG33k** [comment]
I cannot replicate the situation with the creeper; are there any other mods in your pack that deal with death events (that you know of)?

EDIT: And/or do you remember if the chat had any specific messages about the death relation to the grave?

**Comment by SilentChaos512** [comment]
I can replicate this consistently with TNT, although it doesn't seem to be dropping the grave block in this case. I don't know of anything using death events in the pack. The message indicating the place of death is being displayed, however.
