### ISSUE TITLE
[Suggestion] Mod Support for Expandable Backpacks and Cosmetic Armor Reworked

### ISSUE THREAD

**Issue by WenXin20** [M4thG33k/TombManyGraves#12]
Expandable Backpacks Mod:
http://minecraft.curseforge.com/projects/expandable-backpacks

Cosmetic Armor Reworked Mod:
http://minecraft.curseforge.com/projects/cosmetic-armor-reworked

**Comment by M4thG33k** [comment]
The mod should already be compatible with Cosmetic Armor (unless they changed something on their end which broke compatibility), but I'll take a look at both of these later this week.

**Comment by WenXin20** [comment]
Thanks, for Cosmetic Armor, I noticed that sometimes the armor fell on the ground and sometimes it didn't.

**Comment by M4thG33k** [comment]
Is that still true with the newest versions of the mod?

**Comment by WenXin20** [comment]
I'm not sure, but it seems to work fine.

**Comment by Boingboingsplat** [comment]
Using the newest versions of both mods (TombManyGraves-1.9.4_1.10.2-2.1.8 and Expandable Backpacks 1.1.8) the gravestones still do not capture the backpack if it's stored in the backpack slot.

**Comment by M4thG33k** [comment]
I've been a bit of a slacker since my wedding last month...I'll try to look into this tomorrow and see if I can add compatibility to Expandable Backpacks easily enough.

**Comment by M4thG33k** [comment]
Sorry for the late work here, but I can't add compatibility with Expandable Backpacks until they fix a bug that deletes Soulbound-enchanted items.

**Comment by WenXin20** [comment]
Ok

**Comment by Doragoon01** [comment]
What about the similar but simpler backback mod

**Comment by Doragoon01** [comment]
What about Eydamos's backback mod?
https://minecraft.curseforge.com/projects/forge-backpacks

**Comment by WenXin20** [comment]
Expandable Backpacks fixed the soul-bound bug

**Comment by M4thG33k** [comment]
@WenXin20 I saw that. If nothing comes up with work today, I can try to get the compatibility working this afternoon.

@Doragoon01 I can take a look at adding that compatibility as well.

**Comment by WenXin20** [comment]
Ok thanks

**Comment by M4thG33k** [comment]
@WenXin20 @Doragoon01  The newest version adds support for both of the backpack mods. Let me know if anything is broken! :-)

**Comment by VallenFrostweaver** [comment]
@M4thG33k Currently Cosmetic Armor Reworked (v1a) and TMG (v3.03) are not working together. Any cosmetic armors are dropped on the ground.
![grave](https://cloud.githubusercontent.com/assets/13642054/24610556/e920cf5e-1876-11e7-9ed0-5b4f7435c00c.png)

**Comment by M4thG33k** [comment]
Version 3.0.0+ of TMG has its own issue tracker: https://github.com/M4thG33k/TombManyGraves2/issues

This is because TMG2 was re-written slightly from prior versions. Please post this issue there instead. Thank you.
