### ISSUE TITLE
[1.10.2] Soulbound items deleted on death

### ISSUE THREAD

**Issue by kwpugh** [M4thG33k/TombManyGraves#13]
Forge: 2018
Mod: TombManyGraves-1.9.4_1.10.2-2.1.8.jar

Items enchanted with Soulbound are deleted from player and grave.

**Comment by M4thG33k** [comment]
I'll take a look at this this week; Ender IO might have changed the soulbound enchant in newer versions as this has worked in the past. Hopefully I can figure it out quickly. :-)

**Comment by psychofad** [comment]
Just gonna make a comment.

When I died with soulbound items on me, I could see just the soulbound items in my hotbar before I pressed the respawn button.  After I pressed it they were deleted from existence.  It seems that I am dropping everything else into the grave.  Do you possibly delete the inventory at respawn?

**Comment by M4thG33k** [comment]
I don't deal with anything during respawn. The grave takes items from the inventory upon death (before items drop from the inventory); I know the Soulbound enchant deals with respawn inventory. I can try to look into this more deeply after I finish my move in a week.

**Comment by M4thG33k** [comment]
I was unable to reproduce this issue with only TMG installed. I did, however, discover a bug with a certain backpack mod that was deleting soulbound items and reported it to that author (and it has since been fixed).
