### ISSUE TITLE
Graves and their placement when suffocating in a portal incicent

### ISSUE THREAD

**Issue by utoc** [M4thG33k/TombManyGraves#14]
Greetings!

We're having a slight issue caused by another mod that causing erratic nether portal behavior and most of the time you're left in solid netherrack and suffocate to death.  We've noticed though that when a player suffocates, most of the time we can't find a grave.  I can't confirm that there are never any but even resorting to the XRay mod, we're unable to find it.  Can you make a small change that would give coords for the grave if they died in a wall.. or some other kind of change to this?

The /tmg_restore command works great in these cases though!  So thanks for that.

**Comment by M4thG33k** [comment]
Items should be spilling on the ground of a grave isn't formed, so that's interesting. 
Are the coordinates neither displayed in chat nor on the server logs? (Assuming both those features are not disabled in the config)

**Comment by utoc** [comment]
```
logs {
    # If true, the log will print the location of a player's death each time they die. (Defaults to true)
    B:printDeathLog=true
}
```

```
[18:43:31] [Server thread/INFO] [TombManyGraves/]: [TombManyGraves]: Shadow3641 died in dimension 0 at (x,y,z) = (-545,80,293). Their grave may be near!
```

So it is logging of death coords but not of grave coords.  I did notice that it looks for an air-gap of 9 blocks in the config.   I'm starting to understand the issue here and we didn't really notice it on the server until we had this mod go awry with portal mechanics.  Where do items spill to when you're suffocated?

**Comment by utoc** [comment]
I understand at this point the mod is working as intended; We'll probably increase the air gap to check for. in these cases.
