### ISSUE TITLE
Server Crash 

### ISSUE THREAD

**Issue by whatthedrunk** [M4thG33k/TombManyGraves#15]
Some users seem to be crashing the server with the mod installed. When removed it runs fine again. http://pastebin.com/mhY1M5M7

**Comment by whatthedrunk** [comment]
This is still causing issues. http://pastebin.com/Y7g6kFSA

**Comment by M4thG33k** [comment]
Sorry, my life has been busier since my wedding and modding has been sent to the back burner; I'll try to get around to this today if I can make progress in my research.

**Comment by M4thG33k** [comment]
I can't discern the exact problem from these logs. Do you have any idea behind the circumstance of the grave that could be causing this issue?

**Comment by whatthedrunk** [comment]
I can try and get you some more information. Is there an easy way to find the crashing grave? Me and another user are fine in the effected area but one person crashes there if the mod is installed. I was thinking it might be something to do with his computer but because its a server crash it seems to be more then that.

**Comment by M4thG33k** [comment]
The crash seems to be coming from the part of the code dealing with the camo of the block, meaning the block is already constructed. Is there a way for you to determine what the block _under_ the grave is?

**Comment by whatthedrunk** [comment]
Is there a way to find the location of the grave thats causing the issue? I can have someone on the server go to that location now.

**Comment by M4thG33k** [comment]
Depending on which version of the mod you're working with (I can't remember exactly when I implemented it), you can use the "/tmg_getdeathlist [player] <timestamp>" command to get the death list for that specific grave which may include the coordinates. Granted, you'll have to know whose grave it is...and the timestamp (unless you know it was their latest death, then you can use "latest" as the timestamp). You can also tab-complete timestamps if you know approximately when it was created.

**Comment by whatthedrunk** [comment]
I guess it's an RFTools Dimension if that makes it easier to find. They said there shouldn't be any graves in it. There are a ton of deaths I will have to dig though but hoping that I can narrow it down do just searching from the one dim.

**Comment by M4thG33k** [comment]
The crash log does mention that the player DFliyerz was at (x,y,z)=(8.5,64.5,8.5), if that helps at all. (I don't know if that's the person who causes the crash or just someone else affected by it)

**Comment by whatthedrunk** [comment]
Alright when I get off work I will see if I can find out some more info for you, worst case I will just delete the dim that's causing issues.

**Comment by M4thG33k** [comment]
Sorry if it comes to that :-/

**Comment by whatthedrunk** [comment]
Now they are saying "to get the crash you'll need to go to my mining dimension, then teleport back by both FTB commands and the handheld teleporter from rftools" 

So I don't mind deleting it if we cant figure it out. When I first posted this I thought the server was just crashing when they came close to a grave.

**Comment by M4thG33k** [comment]
That seems like a good idea. That sounds very convoluted. Haha

**Comment by whatthedrunk** [comment]
Can't seem to replicate it so I will close this, thanks for your help anyway!
