### ISSUE TITLE
Baubles Crash on Grave forum

### ISSUE THREAD

**Issue by Phonavis** [M4thG33k/TombManyGraves#16]
Baubles 1.2.1.0
Tomb Many Graves 2.1.8
MC 1.10.2
Crash log- http://puu.sh/r6ZAZ/cd211adbf6.txt

**Comment by M4thG33k** [comment]
My life has been busier since my wedding and modding has been sent to the back burner; I'll try to get around to this today if I can make progress in my research.

**Comment by M4thG33k** [comment]
I haven't been able to reproduce this bug
