### ISSUE TITLE
New version breaks /help

### ISSUE THREAD

**Issue by C0rn3j** [M4thG33k/TombManyGraves#18]
http://pastebin.com/En7B1PAq

This is how LootBags fixed the same issue on their side.
https://github.com/Malorolam/LootBags/commit/2647147688ea02e3de88c87e5e927a5e2dbfd6c8

**Comment by M4thG33k** [comment]
Hmm...I thought I had already done this. I'll post a new build shortly.

**Comment by C0rn3j** [comment]
Works fine, thanks!
