### ISSUE TITLE
Crash w/ Baubles 1.3 Beta 7

### ISSUE THREAD

**Issue by WenXin20** [M4thG33k/TombManyGraves#19]
I crashed when I died w/ [Baubles 1.3 Beta 7](https://minecraft.curseforge.com/projects/baubles)
Forge 2092
[Crash Log](http://pastebin.com/TT3FzBT9)

**Comment by M4thG33k** [comment]
I haven't had a chance to update with Bauble's new release yet.

**Comment by WenXin20** [comment]
Ok

**Comment by number5** [comment]
Had exactly the same error with Baubles-1.10.2-1.3.BETA9.jar (when I been killed in game)

I didn't want to update Baubles but Botania r1.9-330.jar now required 1.3 beta version of Baubles

**Comment by M4thG33k** [comment]
I plan on getting an update ready later today. ^_^

**Comment by M4thG33k** [comment]
The update going live in a few minutes will fix the issue with Baubles, however due to the structure of both mods, any/all Baubles stored inside graves upon update will be lost (forever). So be wary of that upon updating.

**Comment by WenXin20** [comment]
Ok, thanks
