### ISSUE TITLE
Does not allow for soulbound enchant.

### ISSUE THREAD

**Issue by spdkils** [M4thG33k/TombManyGraves#2]
A few mods, like Ender IO, add an enchant soulbound. To keep your stuff after death. This mod, triggers 1st, and doesn't allow soulbound to function.

**Comment by M4thG33k** [comment]
Ooh. I forgot about that. I'll see what I can do. Thanks for bringing this to my attention!

**Comment by spdkils** [comment]
https://github.com/SleepyTrousers/EnderIO/blob/c70377e3e3325f701630d9cd46b70257a41fcf2f/src/main/java/crazypants/enderio/enchantment/EnchantmentSoulBound.java

**Comment by M4thG33k** [comment]
Yup. I know a fix, I just need to get to my computer sometime. 😊

**Comment by spdkils** [comment]
Sweet, I'll watch for the changes. (Curious how you will fix it.)

**Comment by M4thG33k** [comment]
Are you still using the 1.9 version?

**Comment by spdkils** [comment]
I was actually running the 1.9.4 version. I didn't see you had two git.

**Comment by M4thG33k** [comment]
No problem. That just means I only have to update one version. 😊
I will probably have a fix out within 24 hours. I wasn't able to code at all today.

**Comment by M4thG33k** [comment]
The next update should fix this issue. (Read the change log for more explanation as to how it will work...-ish...)
