### ISSUE TITLE
Support for Thut Wearables Mod

### ISSUE THREAD

**Issue by WenXin20** [M4thG33k/TombManyGraves#20]
The mod adds a gui to the player inventory similar to baubles.
[Mod Link](https://minecraft.curseforge.com/projects/thut-wearables)

**Comment by M4thG33k** [comment]
I'll take a look at it later this week.

**Comment by WenXin20** [comment]
Ok, thanks

**Comment by M4thG33k** [comment]
The update going live will have support for Thut's Wearables
