### ISSUE TITLE
crash on death in nether 

### ISSUE THREAD

**Issue by 5kedone** [M4thG33k/TombManyGraves#22]
http://pastebin.com/YsQcf4PL

**Comment by M4thG33k** [comment]
Which version of TMG are you using?

**Comment by jprocket45** [comment]
This is not just in the nether its crashes no matter where u r on death then if your on a server its crashes the server if you die in it. ver 1.11    I reverted back to 1.10 no issues

**Comment by M4thG33k** [comment]
What version of Baubles were/are you using?

**Comment by ShneekeyTheLost** [comment]
Yea, I just crashed in the overworld on death from a baby zombie while standing in water in 1.11. Might want to check that version. Rolling back to 1.10 in the meantime.

**Comment by M4thG33k** [comment]
What version of Baubles was being used?

**Comment by ShneekeyTheLost** [comment]
Baubles version 1.9.4-1.2.1.0, latest release for 1.10.2, unless you're building off of alphas

**Comment by M4thG33k** [comment]
Yes, I have built upon the alphas (Botania requires the newest versions of Baubles and so an update was necessary). I'll try to add this information to the changelog

**Comment by ShneekeyTheLost** [comment]
Not sure how Botania's update is going to impact yours, but that's good to know.

**Comment by M4thG33k** [comment]
A lot of people using TMG are also using the newest version of Botania and so the older version of TMG was causing crashes for them.
