### ISSUE TITLE
Grave collision

### ISSUE THREAD

**Issue by PONYRYDE** [M4thG33k/TombManyGraves#23]
On walking into a grave I crash with this

com.m4thg33k.tombmanygraves.tiles.TileDeathBlock.replaceExpandableBackpack(TileDeathBlock.java:511)
 com.m4thg33k.tombmanygraves.tiles.TileDeathBlock.onCollision(TileDeathBlock.java:334)
com.m4thg33k.tombmanygraves.blocks.BlockDeath.func_180634_a(BlockDeath.java:156)

with Expandable Backpacks installed.

Using 1.10.2-2.1.11

**Comment by M4thG33k** [comment]
Can I have the full crash log?

**Comment by PONYRYDE** [comment]
Also if the grave is set to swap life is good.

[crash-2016-10-16_10.40.48-server.txt](https://github.com/M4thG33k/TombManyGraves/files/531549/crash-2016-10-16_10.40.48-server.txt)

**Comment by PONYRYDE** [comment]
There might be a Baubles dependency too. Without Baubles I can't respawn with this (doesn't crash)

[tmg-error.txt](https://github.com/M4thG33k/TombManyGraves/files/531634/tmg-error.txt)

Fresh install with just TMG.

**Comment by M4thG33k** [comment]
Interesting. I'll have to take a look at this tomorrow.

**Comment by M4thG33k** [comment]
I think I have a fix for both of these issues. A new version is going live shortly.

**Comment by M4thG33k** [comment]
Let me know if the new version doesn't work. I couldn't replicate the first crash.

**Comment by PONYRYDE** [comment]
Both issues seem fixed. It's time to give yourself a pat on the back. :+1:
