### ISSUE TITLE
Crash on death

### ISSUE THREAD

**Issue by vrork** [M4thG33k/TombManyGraves#24]
I crash everytime i die. It seems to be related to Baubles

http://pastebin.com/RHkYCyEs

**Comment by M4thG33k** [comment]
TombManyGraves 1.10.2-2.1.11 is NOT COMPATIBLE with the 1.9.4 versions of Baubles. Please read the changelogs before updating.

**Comment by vrork** [comment]
And if i update to any of the other versions of baubles, my whole game bugs (or i die and cant respawn, or i am in half creative mode (cant interact in any way with mobs of any kind)

**Comment by M4thG33k** [comment]
So don't update TombManyGraves. Use 1.10.2-2.1.10 instead, which IS compatible with the old versions of Baubles.

**Comment by vrork** [comment]
Thanks.

Em 15/10/2016 23:17, "M4thG33k" notifications@github.com escreveu:
