### ISSUE TITLE
Giant "Red" Texture hogs the Texture Atlas

### ISSUE THREAD

**Issue by FliegendeWurst** [M4thG33k/TombManyGraves#29]
Here's the texture atlas of my custom 1.10 pack.
![textures_mipmap_0](https://cloud.githubusercontent.com/assets/12560461/20029230/0299276a-a347-11e6-8886-6598b7ea765c.png)

As you can see, TombManyGraves takes up a big amount of space in the middle area, wasting a lot of it with a single color texture.

Here's the new mod to dump textures if you want to try it out: https://github.com/mezz/TextureDump
Also: https://www.reddit.com/r/feedthebeast/comments/5b6bwg/exploring_the_texture_map/

**Comment by M4thG33k** [comment]
Yeah, I completely forgot about that. I'll remove that in the next build.
