### ISSUE TITLE
Dying inside a Tinker's Construct Smeltery Crashes the Client/Prevent World Access

### ISSUE THREAD

**Issue by Lanolin** [M4thG33k/TombManyGraves#3]
I discovered a bug while playing around with TombManyGraves and Tinker's Construct.

Crash Log after death by smeltery:
http://pastebin.com/k5u5adt2

Crash Log after attempting to access the same world:
http://pastebin.com/ZbLPK2K3

TombManyGraves version: 1.9.4-2.1.0
Tinker's Construct version: 1.9.4-2.3.1

Removing TombManyGraves before logging into the world allows access again. I cleared out the smeltery and readded the TombManyGraves. This fixed the crashes and left an invisible "entity" where my grave was. I wasn't sure if I could access it or not as I didn't feel like waiting around for the items to be given to me (a bug(?) I also reported). I was able to give myself my items from death using the "/tmg_restore [player] latest" command.

**Comment by M4thG33k** [comment]
Interesting. I'll try to take a look at this on Monday. A few details: what size was the smeltery and did it have any molten metals inside at the time of death? Were you inside the smeltery structure or just near it? (I need to attempt to recreate the issue so I can better understand what's going on.) Thanks for letting me know!

**Comment by Lanolin** [comment]
It had molten metals in it, yes. It was a 2x2 Smeltery (inside "usable" space). I got stuck inside and couldn't mine my way out as I was "underwater". I'd say just fill a smeltery with molten metals and jump in!

**Comment by M4thG33k** [comment]
Thanks! I'll try to have a fix out Monday evening at the latest (assuming all goes according to schedule on my end...)

**Comment by M4thG33k** [comment]
I'm unable to replicate this bug. What version of Forge are you using?

**Comment by Lanolin** [comment]
Forge Version 12.17.0.1951

**Comment by M4thG33k** [comment]
Try updating to 12.17.0.1954 and see if you have the same problem.

**Comment by Lanolin** [comment]
Updated and tested. After throwing myself into the smeltery (for science!) I ran into NO issues. I tried this with items in my inventory and without. Dying inside the smeltery (with items in my inventory) seems to temporarily disable the multiblock. Hooray!

**Comment by M4thG33k** [comment]
I'm not sure what was causing the issue before, but I'm glad it doesn't exist in the newest version of Forge! Thanks for letting me know of issues; if you find any more in the future (or have suggestions), please let me know!
