### ISSUE TITLE
Incompatability with some "soulbound" items

### ISSUE THREAD

**Issue by VoodooBeard** [M4thG33k/TombManyGraves#30]
I am playing a 1.10.2 pack (HyperAntix) using:
**TombManyGraves-1.10.2-2.1.13**
alongside;
**RandomThings-MC1.10.2-3.7.6
TConstruct-1.10.2-2.5.6b
EnderIO-1.10.2-3.0.1.125_beta**

These mods add, in one way or another, a "soulbound" property to items. The EnderIO soulbound enchantment works perfectly and items are retained by the player.

RandomThings has the Spectre Anchor (https://randomthingsminecraftmod.wikispaces.com/Spectre+Anchor) which you craft with an item to give it an "anchored tag".
Tinker's Construct now has a soulbound modifier (nether star, by default).
Items with either the "Anchored" tag or TC soulbound items both enter the grave on death rather than remaining in the player inventory.

I'm assuming it's an issue somewhat related to this one...
https://github.com/SlimeKnights/TinkersConstruct/issues/2345

Thank you in advance for your help.

**Comment by M4thG33k** [comment]
I have to go in and manually add compatibility with each unique "soulbound" mechanic; I can't guarantee I'll have anything fixed this week, but I will do my best to fix this issue in the next build.

**Comment by VoodooBeard** [comment]
Thanks for update, I know these kinds of things take time :-) 
Is there any way to have it pull from a list in the config to make updating compatibility easier?

**Comment by M4thG33k** [comment]
It depends on how each mod handles the mechanic. Assuming they all use some sort of NBT tag (which is the only way I know of to deal with it), then it's very possible. But, again, I can't promise anything at the moment. :-)

**Comment by VoodooBeard** [comment]
Look forward to the update. Thanks again :-)

**Comment by taj1994** [comment]
Any update on this? I keep losing my Tinkers' Construct tools that have Soulbound on them...

**Comment by VoodooBeard** [comment]
Thank you! :-D

**Comment by M4thG33k** [comment]
I should hopefully be uploading the new version to curse later today.
