### ISSUE TITLE
Include location grave placed or failure to create grave in chat message

### ISSUE THREAD

**Issue by Xuerian** [M4thG33k/TombManyGraves#32]
I've had a few issues with a player on my server and things like portal suffocation, then finding his stuff again.

It'd be great if the location of the created grave or a message indicating failure to find a suitable spot were included in the chat message.

**Comment by M4thG33k** [comment]
If a grave is created, a chat message is sent to that player giving the coordinates (it's also printed in the server log) as well as being available in the Death Item List that is given to the player when respawnining. If a grave is not formed, that message is also already displayed to that player.

**Comment by M4thG33k** [comment]
(Unless, of course, one of the forge updates broke everything)

**Comment by Xuerian** [comment]
Well, the issue we had was this outstanding bug: https://bugs.mojang.com/browse/MC-98153 related to this issue https://github.com/M4thG33k/TombManyGraves/issues/14
I searched from outside the top of the nether to the bottom and didn't find the grave at the X/Z indicated.

But, if it's already supposed to work that way that's fine, sorry for requesting existing features. I wouldn't sweat the edge case.
