### ISSUE TITLE
Gravestone destroyable by Wither (and drops grave-block)

### ISSUE THREAD

**Issue by ghost** [M4thG33k/TombManyGraves#37]
I was attempting to fight the Wither Boss in the nether when he escaped containment and killed me. By the time I got back to the area, my grave was exploded and my items (plus the grave-block item) were strewn across the ground.

As it didn't pop while I was still in death screen, but was by the time I got back, my assumption here is that it was caught in the blast radius of one of the blue skulls.

**Comment by M4thG33k** [comment]
Interesting, since the block is marked indestructible. I'll try to take a look at it when I get home after Christmas.

**Comment by M4thG33k** [comment]
See message on other issue.
