### ISSUE TITLE
Placing grave-block crashes world

### ISSUE THREAD

**Issue by ghost** [M4thG33k/TombManyGraves#38]
Placing the grave-block (ontained through Wither Boss #37) crashed the world but I sort of expected that.

Potentially add a sanity-check to when the block is placed such that when a player places it, it immediately erases itself instead of proceeding to the point it causes the crash? Or at least such that the world will be reloadable after the initial crash.

**Comment by M4thG33k** [comment]
I thought I had already made the item block unable to be placed in the world...I'll double-check that code.

**Comment by ghost** [comment]
Forgot to mention the mod version: 1.9-1.0.3

The modpack is New Beginning (a skyblock pack on Curse)

**Comment by M4thG33k** [comment]
Wow, that's a really outdated version. I'll see what I can do though, if people are still using that version of MC on a regular basis...

**Comment by M4thG33k** [comment]
I've decided not to go back and fix the 1.9.4 versions as most people are tending toward 1.10+ now.
