### ISSUE TITLE
Add compatibility with Cosmetic Armor Reworked

### ISSUE THREAD

**Issue by patrickclank9** [M4thG33k/TombManyGraves#4]
http://minecraft.curseforge.com/projects/cosmetic-armor-reworked
Currently drops and sometimes deletes items in the cosmetic armor slots.
![2016-06-18_15 28 11](https://cloud.githubusercontent.com/assets/5445944/16174094/85513040-3569-11e6-9a34-50ba1472db15.png)
![2016-06-18_15 29 17](https://cloud.githubusercontent.com/assets/5445944/16174095/8a3f8bec-3569-11e6-91a7-3dc60f671468.png)

**Comment by M4thG33k** [comment]
interesting. I'll try to take a look at that later this week. Thanks for bringing this to my attention!

**Comment by patrickclank9** [comment]
Well thanks for making the best gravestone mod ever :)
