### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by magnusjjj** [M4thG33k/TombManyGraves#42]
Hi!

Your mod is listed as being GPLv3.

But, your curseforge page has the following statement in it:

"You are free to use this mod in any/all mod packs as long as you 1) don't make profit from it, 2) don't claim that you made it, and 3) let me know that you're using it. (The third is optional, but preferred.)"

The GPLv3 license has the following in it:

"All other non-permissive additional terms are considered "further
restrictions" within the meaning of section 10.  If the Program as you
received it, or any part of it, contains a notice stating that it is
governed by this License along with a term that is a further
restriction, you may remove that term.  If a license document contains
a further restriction but permits relicensing or conveying under this
License, you may add to a covered work material governed by the terms
of that license document, provided that the further restriction does
not survive such relicensing or conveying."

Just thought you might want to know :). 'Claiming you created it' is already in laws regarding fraud and copyright already as well :).
Not planning to steal your work, or sell it, or anything, just a.. license nerd extraordinare ;).

That being said, there is no license term against you having that notice on your curseforge page, its just that you have already given the world a license to ignore the notice. *bumbles ahead*

**Comment by M4thG33k** [comment]
I figured most people won't care about/read the actual license and don't want to keep answering the "can I use this..." question. What would you suggest in place of the line on Curseforge? 

"You may use this mod alone or in a pack in accordance to its license. Feel free to let me know you're including it in a pack; it's fun for me to see how it's being used!"

**Comment by magnusjjj** [comment]
Sure ^^. Sounds friendly and nice :D.

Oh, reason I stubled across this is, i guess, me making my.. uh. second modpack, and went trough the whoooooole list of mods in resonant rise and dug through the licenses and the source places, and made a huge google sheet with the info = slightly nuts at this point. Every mod, seperate licenses.)

**Comment by M4thG33k** [comment]
That sounds like a huge pain. Haha
