### ISSUE TITLE
Crash to desktop. open door with death note in hand. [1.10.2]

### ISSUE THREAD

**Issue by demethan** [M4thG33k/TombManyGraves#45]
Hi, 

one of our users on our server posted this crashlog http://pastebin.com/i50qHdSw

She said that she tried opening a door with the death note in hand. 

[All the mods - Expert 1.23]

Thank you .

**Comment by M4thG33k** [comment]
I don't see anything in the stack trace that hints toward TMG being the problem; it looks like the issue comes from the crafting handler (which I don't even touch). Is the issue repeatable?

**Comment by demethan** [comment]
I can't reproduce the problem.
