### ISSUE TITLE
Crash loop

### ISSUE THREAD

**Issue by IchigoGames** [M4thG33k/TombManyGraves#46]
not sure if this crash has already been reported but some one on my server was in a crash loop and it looks like it has to do with this mod heres the crash report http://pastebin.com/d8CcG2hN

running 
TombManyGraves-1.11.2-3.0.0
Forge 2255
minecraft 1.11.2

**Comment by M4thG33k** [comment]
This issue is for a different version of the mod. I've opened the issue on the appropriate page.
