### ISSUE TITLE
/tmg_restore deteles previous inventory

### ISSUE THREAD

**Issue by GreatestFool** [M4thG33k/TombManyGraves#48]
My gravestone didn't spawn properly while fighting the Chaos Dragon and I ended up using "tmg_restore" I used the latest one but instead of adding the items into their slots as I thought it would, it instead deleted my entire inventory and replaced it with the 3 items that were not soulbound.

Wat. Is there a way to restore the inventory now? Or is it supposed to do that? I ended up reverting my inventory to an earlier point but still, thought it might be worth to mention if it isn't supposed to do that.

**Comment by M4thG33k** [comment]
The "tmg_restore" command changes the player's inventory to that stored in the grave (according to the backup file), so this is working correctly.

The "tmg_drop" command will drop the contents of the backup at that player's feet instead (this is the command you want to use if a grave doesn't form correctly).

**Comment by GreatestFool** [comment]
Ah, I didn't see anything mentioning this on the project page so I just assumed it worked like normal, thanks for clearing up that misunderstanding.

**Comment by M4thG33k** [comment]
No problem!
