### ISSUE TITLE
No grave when bled to death

### ISSUE THREAD

**Issue by RaineAndrews** [M4thG33k/TombManyGraves#8]
When bats suck your blood to death, no grave is created and no death message is stated.  I imagine this has to do with how the Rough Mobs mod handles the bat damage.  Maybe it isn't thought?

**Comment by M4thG33k** [comment]
Interesting. I'll see if I can figure this out; the mod doesn't have a public code repository, so it may be a bit difficult to pinpoint the issue.

**Comment by M4thG33k** [comment]
Also, which version of both mods are you using?

**Comment by RaineAndrews** [comment]
1.94
forge 12.17.0.1987
Rough Mobs 1.0
Tomb Many Graves 2.1.5

**Comment by M4thG33k** [comment]
Thanks!

**Comment by RaineAndrews** [comment]
The obvious work-around for now it to disable their blood sucking through the configs, but it was a neat trick :(

**Comment by M4thG33k** [comment]
Hopefully I can work around it in-code. Give me a little while. ;-)

**Comment by M4thG33k** [comment]
I was unable to recreate this bug. I let a bat suck my brain dry and the grave spawned in the correct spot. I'm also using the 2.1.6 version of TMG, but the update only added features and doesn't affect how graves spawn (unless underwater)

**Comment by M4thG33k** [comment]
Edit: I have experienced it now. I'll keep working

**Comment by M4thG33k** [comment]
The mod seems to be cancelling the event I use to spawn the graves; I'll see if I can find out why/how they are doing this.

**Comment by M4thG33k** [comment]
This is an issue within Rough Mobs; they say they've fixed it.
